name: CI
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity (tree + versions)
        run: |
          python -V
          pip -V
          ls -la
          echo "---- data ----"
          ls -la data || true

      - name: Unit tests
        run: python -m pytest -q -vv

      - name: Smoke import (headless)
        env:
          STREAMLIT_SERVER_HEADLESS: "true"
        run: |
          python - << "PY"
          import importlib
          importlib.import_module("streamlit_app")
          print("app import ok")
          PY
